"""add contact consent tracking

Revision ID: 1681930e4c90
Revises: e3280ed236e9
Create Date: 2026-09-23 13:21:25.437825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1681930e4c90'
down_revision = 'e3280ed236e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_given', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('consent_given_at')
        batch_op.drop_column('consent_given')

    # ### end Alembic commands ###
